drop table dehuser1111.CARDS_ACCOUNTS_MASTER
/

drop synonym dehuser1111.CACC
/

create table dehuser1111.CARDS_ACCOUNTS_MASTER
(
	DB_TS NUMBER(5,0) , 
	BANK_ID NVARCHAR2(11) , 
	PROSPECT_ID NUMBER(10,0) ,
	LEAD_NUMBER NVARCHAR2(50) ,
	REQ_DETAILS CLOB, 
	FREE_TEXT_1 NVARCHAR2(50) ,
	FREE_TEXT_2 NVARCHAR2(50) ,
	FREE_TEXT_3 NVARCHAR2(50) ,
	FREE_TEXT_4 NVARCHAR2(50) ,
	FREE_TEXT_5 NVARCHAR2(50) ,
	DEL_FLG CHAR(1) ,
	R_CRE_ID NVARCHAR2(65) ,
	R_CRE_TIME DATE ,
	R_MOD_ID NVARCHAR2(65) ,
	R_MOD_TIME DATE,
	WORKITEM_NO NVARCHAR2(50) , 
	IS_CUSTOMER_NTB CHAR(1 BYTE),
	UPLOAD_FLAG CHAR(1 BYTE), 
	DROP_EMAIL_FLAG CHAR(1 BYTE), 
	DROP_EMAIL_TIME NVARCHAR2(100), 
	WELCOME_FLAG CHAR(1 BYTE)
) 
TABLESPACE MASTER
/

create synonym dehuser1111.CACC for dehuser1111.CARDS_ACCOUNTS_MASTER
/

CREATE UNIQUE INDEX INDX_CACC ON CACC(BANK_ID,PROSPECT_ID)
TABLESPACE IDX_MASTER
/
