name: Database cd

on:
 workflow_dispatch:
 
env: 
  Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
  
jobs:
  caller-Database-deploy:
     runs-on: self-hosted
     steps:
      - name: Trigger Caller Workflow
        uses: lf-common-repo/shared-workflow/.github/workflows/databaseci.yml@main
     
     
