name: Database CI

on:
 workflow_dispatch:
 
 
jobs:

    trigger_databaseci: 
      
       uses: lf-common-repo/shared-workflow/.github/workflows/databaseci.yml@main
      
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
