name: Oracle Database Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        "C:\app\db\bin\sqlplus.exe" viveksundar5/Svs@9551@orclpdb @.\deploy.sql
