name: Oracle Database Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy Oracle Database
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check sqlplus location
      run: |
        which sqlplus

    - name: Deploy
      run: |
        sqlplus -s ${{ secrets.username }}/${{ secrets.password }}@orcldr @./deploy.sql
      env:
        ORACLE_SID: orclpdb

