name: build,test,upload sql server

on: 
  workflow_dispatch

env:
  TOKEN: ${{ secrets.SONAR_TOKEN }}
  URL: ${{ secrets.SONAR_HOST_URL }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
          
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Reformat SQL Files
        uses: credfeto/action-sql-format@v1.4.1
          
     
          

          
      - name: Test
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"sql-server-test" /d:sonar.login="$env:TOKEN" /d:sonar.host.url="$env:URL"
          dotnet build
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="$env:TOKEN"
          
          
      - name: Publish to GitHub Packages
        run: |
          gh package publish --target 'mysql-database-script' deploy.sql
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
