name: Oracle Database Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy Oracle Database
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        sqlplus -s ${{ secrets.username }}/${{ secrets.password }}@orcle @./deploy.sql
      env:
        ORACLE_SID: orcle

