name: SQL Deployment

on:
 workflow_dispatch

jobs:
  deploy_sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SQL Server tools
      run: |
        sudo apt-get update
        sudo apt-get install -y mssql-tools

    - name: Run SQL Deployment Script
      run: |
        sqlcmd -S server -U username -P password -d database -i deploy.sql

    - name: Publish to GitHub Packages
      run: |
        echo "registry=https://nuget.pkg.github.com/YOUR_USERNAME/index.json" >> ~/.npmrc
        echo "//npm.pkg.github.com/:_authToken=\${{secrets.GITHUB_TOKEN}}" >> ~/.npmrc
        npm publish

      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN }}
