name: Oracle Database Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        sqlplus -s username/password@your_oracle_db @path/to/deploy.sql
      env:
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}

    
