name: Oracle Database Deployment

on:
 workflow_dispatch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        sqlplus -s viveksundar5/Svs@9551@orclpdb @./deploy.sql
      env:
        ORACLE_HOME: ${{ env.ORACLE_HOME }}
        LD_LIBRARY_PATH: ${{ env.LD_LIBRARY_PATH }}
      shell: bash
