name: Oracle Database Deployment

on:
  workflow_dispatch

jobs:
  deploy:
    name: Deploy Oracle Database
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy
      run: |
        & "C:\app\db\bin\sqlplus.exe"  ${{ secrets.username }}/${{ secrets.password }}@orcldr @./deploy.sql
      env:
        ORACLE_SID: orclpdb

