name: Database

on:
  workflow_dispatch

env:
  TOKEN: ${{ secrets.SONAR_TOKEN }}
  URL: ${{ secrets.SONAR_HOST_URL }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install SonarScanner
        run: |
          curl -sSLo /tmp/sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
          unzip -q /tmp/sonar-scanner-cli.zip -d /tmp
          mv /tmp/sonar-scanner-4.6.2.2472-linux /tmp/sonar-scanner
          echo "export PATH=\$PATH:/tmp/sonar-scanner/bin" >> $GITHUB_ENV
          echo "SonarScanner installation completed."

      - name: Debugging
        run: |
          echo "PATH: $PATH"
          which sonar-scanner
        shell: /usr/bin/bash -e {0}

      - name: Grant execute permission
        run: chmod +x deploy.sql

      - name: SonarCloud Analysis
        run: |
          # Run SonarCloud analysis
          sonar-scanner -Dsonar.login=$TOKEN -Dsonar.host.url=$URL

      - name: Publish to GitHub Packages
        run: |
          # Create a ZIP archive of the deploy.sql file
          zip -r deploy.sql.zip deploy.sql

      - name: Upload ZIP to GitHub Packages
        uses: actions/upload-artifact@v2
        with:
          name: deploy-sql
          path: deploy.sql.zip
