name: Database

on:
  workflow_dispatch

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
  
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
       
      - name: Grant execute permission
        run: chmod +x deploy.sql

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}


      - name: Create Zip
        run: |
          # Create a ZIP archive of the deploy.sql file
          zip -r deploy.sql.zip deploy.sql
          
      - name: Upload ZIP to artifact
        uses: actions/upload-artifact@v2
        with:
          name: deploy-sql
          path: deploy.sql.zip

      - name: Publish package
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW2_PAT_TOKEN_GITHUB }}
        run: |
         curl -X PUT -H "Authorization: token $GITHUB_TOKEN" -H "Content-Type: application/zip" --data-binary @deploy.sql.zip "https://maven.pkg.github.com/lf-retail/database/com/example/my-artifact/1.0/deploy-sql-1.0.zip"

